# Input/output configuration
input_dir: ${EXATRKX_DATA}/embedding_processed/docker_test
output_dir: ${EXATRKX_DATA}/gnn_processed/docker_test
project: GNNComparisons
edge_cut: 0.5

# Dataset parameters
pt_min: 1.0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset
datatype_split: [[3, 1, 1]] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
hidden: 64
n_graph_iters: 8
nb_node_layer: 2
nb_edge_layer: 2
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
delta_eta: 1.2
warmup: 100
lr: 0.001
factor: 0.3
patience: 50
regime:
    - non_ci # This is to NOT include cell information. Switch comment with "ci" to include cell information
#     - ci
    - pid
max_epochs: 5
slack_alert: False

# Post-processing
callbacks: [] #[GNNInferenceCallback]

# Logging
wandb_save_dir: ${EXATRKX_DATA}/wandb_data
